David-OConnor/pyflow

Cargo.lock
Cargo.toml
src/util.rs

This PR proposes using rust-ini to parse the .gitconfig file instead of reading line by line. 
This also fixes issue #23, in which the value read from the 'name' field under `[user]` would be overwritten by any subsequent `name` field.

Use rust-ini to read gitconfig

---

src/main.rs

```
$ pyflow help install
Install packages from `pyproject.toml`, `pyflow.lock`, or speficied ones. Example:
`pyflow install`: sync your installation with `pyproject.toml`, or `pyflow.lock` if it exists.
`pyflow install numpy scipy`: install `numpy` and `scipy`.
```
This description has no information about options or arguments. I changed it to display such information like any other command.
```
$ pyflow help install
pyflow-install 0.1.9
Install packages from `pyproject.toml`, or ones specified
USAGE:
pyflow install [FLAGS] [packages]...
FLAGS:
-d, --dev        Save package to your dev-dependencies section
-h, --help       Prints help information
-V, --version    Prints version information
ARGS:
<packages>...    
```

Improve the help message for install command

---

src/main.rs

When `pyflow new foo-bar` is executed, pyflow creates `foo-bar/foo-bar/__init__.py`. But python package name are not used `-`. We use `_` instead. So pyflow should create `foo-bar/foo_bar/__init__.py`
cf. `poetry new foo-bar` creates `foo-bar/foo_bar/__init__.py`

replace `-` in package directory name when using new command

---

src/dep_types.rs

I fixed a typo "Pare" to "Parse" in error message.

Fixed a typo

---

README.md

`poetry` also stores dependencies with the project, although this must be configured
globally or locally `poetry config virtualenvs.in-project true --local`.
See https://python-poetry.org/docs/configuration/#virtualenvsin-project-boolean.

Update comparison table

---

src/commands.rs

Hi,
I found that Python code executed by "python" command cannot use stdio since all stdio are captured in pyflow, and felt that it is a little inconvenient. So, I have added stdio support to the python command so that users can benefit from the standard input and output.
Please forgive me for immediately creating a PR without opening an issue.
I hope I can get some feedback from you.
Many thanks.

Add support for stdio in Python code executed by python command

---

src/dep_resolution.rs

Resolves #79
I'm not sure how to print abort messages with multiple colors, but that might be a further enhancement.

Clean up graph creation abort message

---

src/main.rs

#96
(please be gentle, this is my first one)

Fix `pyflow script` crash upon encountering an empty `__requires__`

---

src/dep_resolution.rs

Hi! I noticed some TODO comments about `filter_map`, and this PR addresses them.
Functionally the code remains the same, but this approach avoids calling `Version::from_str` and `Req::from_str` twice. Another thing is that now there is no need for `expect` and `unwrap` - in both cases, they never panicked since that branches always contained `Ok` variants.

Avoid double computation inside some `filter_map` iterators

---

Cargo.lock
Cargo.toml
src/build.rs
src/dep_resolution.rs
src/dep_types.rs
src/files.rs
src/install.rs
src/main.rs
src/py_versions.rs
src/util.rs

:heavy_minus_sign: crossterm
:heavy_plus_sign: termcolor
:heavy_plus_sign: atty
Termcolor allows for turning off colors by setting a ColorChoice. This
commit adds a commandline option to disable colors and also uses atty to
automatically determine if the output is being redirected and disable
colors in that case.

Make color output optional

---

src/main.rs
src/util.rs

Resolves gh-98
an absolute path broke the script_env_path location due to the way
Path.join() works. This also will allow the same script_env_path no matter
if the relative path is used or the absolute path.

pyflow script now uses full path of file for env_path

---

src/dep_parser.rs
src/dep_resolution.rs
src/dep_types.rs
src/main.rs
src/py_versions.rs

The way I went about fixing this introduced some major changes.
The initial issue was that we were trying to pick the correct release version by using our parsed version. That ran into a problem when the version number was `0.07` and parsed down to `0.7.0` and that couldn't find a release version to match. I then thought, why not build a reverse map so we can grab the actual json key based on the parsed `Version`
That worked fine, but I ran into an issue when I was randomly testing package installs and came across a `boltons` package release with the version `0.3.4.dev0`. I looked into the `VersionModifier` code and having seen enums with a type containing a string I thought I would implement that `VersionModifier::Other(String)`. That required me to remove the `Copy` trait and clone the …

Resolve Issue 77

---

src/util.rs

I didn't notice `find_py_version` when I wrote this code. Fixing this repeated logic.

DRY default_python

---

src/dep_parser.rs
src/dep_types.rs
src/py_versions.rs
src/util.rs

This pull request adds the ability to handle `*` requirements in any position. The basics of compatibility work, but I don't know if we are full there with meeting PEP 440. Specifically [Version Matching](https://www.python.org/dev/peps/pep-0440/#version-matching)
Specifically the following case:
```
== 1.1        # Not equal, so 1.1a1 does not match clause
== 1.1a1      # Equal, so 1.1a1 matches clause
== 1.1.*      # Same prefix, so 1.1a1 matches clause
```
This does resolve gh-117 (at least it did for my trial)
```
Found lockfile
Installing toml 0.10.2 ...
Installing typed_ast 1.4.3 ...
Installing appdirs 1.4.4 ...
Installing asgiref 3.3.4 ...
Installing regex 2021.4.4 ...
Installing pathspec 0.8.1 ...
Installing click 8.0.1 ...
Installing uvicorn 0.14.0 ...
Added a console script: …
```

Star requirements

---

src/install.rs

resolves gh-118 and secondary issue in gh-108

fix: tar.gz extracting files without mtime breaking wheel builds

---

README.md

Closes #121
Lmk if you want to keep the existing installation method (removed it since it's missing from the last few releases)

docs: add brew installation

---

src/dep_resolution.rs
src/install.rs
src/main.rs

The contributing guide asks to run `cargo clippy` before submitting PRs. When doing so, I got eight warnings similar to 
```
warning: unknown lint: `clippy::clippy::too_many_arguments`
--> src/install.rs:163:9
|
163 | #[allow(clippy::clippy::too_many_arguments)]
|         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: did you mean: `clippy::too_many_arguments`
```
`clippy` version: clippy 0.1.53 (53cb7b09 2021-06-17)

Remedy warnings generated by clippy

---

src/dep_parser.rs
src/dep_resolution.rs
src/dep_types.rs
src/install.rs
src/main.rs
src/util.rs

- resolves gh-123
- fix regression of DRY default_python
- clean up clippy warnings

Add checking of python compatibility to `get_version_info`

---

src/dep_parser.rs
src/dep_types.rs

came across a python package with the wheel version specfied as `pp257`
this allows it to parse.
- refactored test to use rstest and add that test case

fix `parse_wh_py_ver` to allow 3 or more digits

---

.gitignore
src/files.rs
src/main.rs
src/util.rs

This MR addresses two areas of DRY.
1. `SubCommand::Install` had duplicate code for installing dependencies and dev-dependencies.
2. `files.rs` had duplicate code for adding dependencies/dev-dependencies to `pyproject.toml`.
I should note that some of the tests in `files.rs` have been modified. Previously, it was expecting two newlines (one full blank line plus an additional newline) at the end of the file. I would argue that there should be only one newline.

Resolve some DRY comments

---

Cargo.lock
Cargo.toml
README.md
src/files.rs
src/main.rs
src/script.rs
src/util.rs

Implementation of #130 
Setting a `__python__` variable in your script overrides and overwrites any previously stored version information in `py_vers.txt`. A full Python version specification (X.Y.Z) is required, and the program is aborted if only a partial specification is detected.
This MR also bumps `rstest` to the latest version `0.10.0`, which allows for improved test-writing syntax.

Allow Python version to be set with `__python__` variable in script

---

src/install.rs
src/util.rs

The package `hexdump` fails to install as it does with pip because it lacks a root folder with its archive's name (`hexdump-3.3`). This pull request gives a root folder with that naming scheme to every zip entry without a root folder starting with the name of its package, letting the wheel build and the package install. It also fixes some typos in error messages/comments.
Closes #151.
Notes:
- I fixed (most of) the DRY with the zip detection in `download_and_install_package` by saving any error and checking if an error exists after the entire `match` statement. I do not know if that is acceptable/idiomatic Rust, but it does compile without cloning.
- I pass both `name` and `filename` into `extract_zip` because I don't feel like parsing out the name from `filename` alone when there are …

Give a root folder to source distribution zips without a root folder

---

src/cli_options.rs
src/main.rs

In order to bring API to a more consistent state with other tools, subcommand `add` is presented.
Its attitude is, for now, the same as for `install` subcommand

Adding add

---

src/py_versions.rs
src/util/mod.rs

`python-3.10.2-windows.tar.xz` for `pybin` below. I had to abuse GitHub's upload functionality somewhat hard, but the end justifies the means.
Note: remove the `zip` extension before merging these.
[python-3.10.2-windows.tar.xz.gz.001](https://github.com/David-OConnor/pyflow/files/8228290/python-3.10.2-windows.tar.xz.gz.001.zip)
[python-3.10.2-windows.tar.xz.gz.002](https://github.com/David-OConnor/pyflow/files/8228291/python-3.10.2-windows.tar.xz.gz.002.zip)
[python-3.10.2-windows.tar.xz.gz.003](https://github.com/David-OConnor/pyflow/files/8228302/python-3.10.2-windows.tar.xz.gz.003.zip)

Provide Python 3.10.2 for Windows
